language: python
python:
  - "2.7"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "pypy3"
# commands to install dependencies
install:
  - "pip install 3to2"
  - "pip install ."
  - "pip install -r requirements.txt"
  # Needed to get six >=1.11.0 on Travis
  - "pip uninstall -y six"
  - "pip install six>=1.11.0"
# commands to run tests
script: python setup.py test
